// Curated catalog of lucide-react icon names usable for records/types/tags.
// ponytail: hand-picked list, not a full lucide enumeration — extend as needed.
export const ICON_NAMES = [
  "FileText",
  "Video",
  "Image",
  "Music",
  "Map",
  "Newspaper",
  "Radio",
  "Mic",
  "Camera",
  "Folder",
  "Tag",
  "Star",
  "Calendar",
  "Users",
  "Globe",
  "Archive",
  "Film",
  "BookOpen",
  "File",
  "Clock",
  "Heart",
  "Home",
  "Search",
  "Settings",
  "Bell",
  "Mail",
  "Phone",
  "MessageSquare",
  "Link",
  "Download",
  "Upload",
  "Trash2",
  "Edit",
  "Check",
  "X",
  "Plus",
  "Minus",
  "ArrowRight",
  "ArrowLeft",
  "ChevronDown",
  "User",
  "Lock",
  "Unlock",
  "Eye",
  "EyeOff",
  "Flag",
  "Bookmark",
  "Award",
  "Shield",
  "Database",
  "Server",
  "Cloud",
  "Wifi",
  "Volume2",
  "Play",
  "Pause",
  "Layers",
  "Grid",
  "List",
  "Sun",
  "Moon"
] as const;

export function searchIcons(query: string): string[] {
  const normalized = query.trim().toLowerCase();
  if (!normalized) return [...ICON_NAMES];
  return ICON_NAMES.filter((name) => name.toLowerCase().includes(normalized));
}
