apiVersion: v1
kind: Service
metadata:
  name: {{ include "archive.fullname" . }}-frontend
  namespace: {{ include "archive.namespace" . }}
  labels:
    {{- include "archive.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    {{- include "archive.componentLabels" (dict "component" "frontend" "ctx" .) | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
      protocol: TCP
