apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: archive
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgres-pvc.yaml
  - postgres-statefulset.yaml
  - postgres-service.yaml
  - server-pvcs.yaml
  - server-deployment.yaml
  - server-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - ingress.yaml
  - hpa.yaml
  - network-policy.yaml
