apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: server-files
  namespace: archive
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: server-config
  namespace: archive
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
