import type { AppLocale } from "./types";

const englishLabels: Record<string, string> = {
  "لوحة المتابعة": "Dashboard", "مركز السجلات": "Records center", "تفاصيل السجل": "Record details", "بحث متقدم": "Advanced search", "مستعرض الملفات": "File browser", "حقوق الاستخدام": "Usage rights", "روابط المشاركة": "Share links", "المشاركة الواردة": "Incoming shares", "مركز الإعدادات": "Settings center", "المستخدمون والأدوار": "Users and roles", "المساعدة": "Help", "أول تشغيل": "Getting started", "مركز البيانات": "Data center", "حالة النظام": "System status", "سجل الأخطاء": "Error log", "التحليلات": "Analytics", "التقارير": "Reports", "النشاط": "Activity", "النسخ الاحتياطي": "Backups", "الإشعارات": "Notifications", "المفضلة": "Favorites", "صندوق الوارد": "Inbox", "المشاريع": "Projects", "المجموعات": "Collections", "الوسوم": "Tags", "المفردات": "Vocabulary", "الأنواع": "Types", "سلة المهملات": "Trash", "الرفعات المجدولة": "Scheduled uploads", "إضافة أرشيف": "Add archive", "استيراد المحتوى": "Import content", "التعاون الحي": "Live collaboration", "الأتمتة": "Automation", "الإضافات": "Plugins", "مساعد الأرشيف": "Archive assistant", "خريطة العلاقات": "Relationship map", "الخط الزمني": "Timeline", "الخريطة": "Map", "مقارنة الوسائط": "Media comparison", "مشغل الوسائط": "Media player", "المراجعة المرئية": "Visual review", "مسار الوسائط": "Media workflow", "التفريغ الصوتي": "Transcription", "المكررات": "Duplicates", "البحوث المحفوظة": "Saved searches", "قوالب الأقسام": "Department templates", "قوائم القراءة": "Reading lists", "تفويض الوصول المؤقت": "Temporary access delegation", "المزامنة": "Sync", "سجل المزامنة": "Sync log", "التحكم بالنظام": "System control", "معاينة السلامة": "Safety preview", "مهام المشاريع": "Project tasks", "مشاريع العمل": "Work projects", "يومي": "Daily", "الاكتشاف": "Discover", "الكتالوج العام": "Public catalogue", "عارض المشاركة العامة": "Public share viewer", "رابط مراجعة عام": "Public review link", "تسجيل الدخول": "Sign in",
};

export function localizePageLabel(label: string, locale: AppLocale): string {
  return locale === "en" ? englishLabels[label] ?? label : label;
}
