export const status = {
  errors: { metricsLoad: "تعذر تحميل مقاييس النظام.", unknown: "خطأ غير معروف", healthConnection: "فشل الاتصال بالخادم", connectionPrefix: "خطأ في الاتصال: {message}" },
  uptime: { day: "ي", hour: "س", minute: "د" },
  toolbar: { eyebrow: "مراقبة تشغيلية", title: "حالة النظام", description: "سطح سريع لمراقبة اتصال الخادم ومحرك البيانات ومدة التشغيل، مع تحديث تلقائي كل 30 ثانية.", connected: "متصل", checking: "جارٍ الفحص", disconnected: "غير متصل", lastChecked: "آخر فحص: {date}", checkNowAriaLabel: "فحص الحالة الآن", checkNow: "فحص الآن", viewErrors: "عرض سجل الأخطاء" },
  health: { stable: "الاتصال بالخادم مستقر", checking: "يجري فحص الاتصال", stopped: "الاتصال بالخادم متوقف", defaultDescription: "يعرض هذا السطح صحة الواجهة الخلفية الحالية ونبض الاتصال المباشر.", backend: "الخادم الخلفي", local: "محلي", engine: "محرك البيانات", uptime: "مدة التشغيل" },
  recovery: { healthCheckFailed: "تعذر إكمال فحص الصحة", retry: "أعد الفحص", setupJourney: "ارجع إلى رحلة الإعداد", systemControl: "افتح التحكم بالنظام", serverReady: "خطوة الخادم مكتملة", serverReadyDescription: "اتصال الخادم سليم. اعرض رحلة الإعداد لمعرفة الخطوة التالية ونسبة الجاهزية.", continueSetup: "متابعة رحلة الإعداد" },
  check: { ariaLabel: "تفاصيل الفحص", title: "تفاصيل الفحص", description: "تعتمد هذه البيانات على نقطة `/api/v1/health` دون تغيير في عقد الواجهة الخلفية.", autoRefresh: "تحديث تلقائي", requestStatus: "حالة الطلب", pending: "قيد التنفيذ", success: "ناجح", failed: "فشل", interval: "إيقاع الفحص", intervalValue: "30 ثانية", lastUpdated: "آخر تحديث" },
  metrics: { ariaLabel: "مقاييس الخادم الحية", title: "مقاييس الخادم الحية", description: "المعالج والذاكرة والقرص وعمق قائمة المهام، من `/api/v1/system/status` (للمشرفين فقط).", cpu: "حمل المعالج", memory: "الذاكرة", disk: "القرص", queueDepth: "عمق قائمة المهام", unavailable: "غير متاح", loadError: "تعذر تحميل مقاييس النظام" },
  disasterRecovery: { ariaLabel: "جاهزية التعافي من الكوارث", title: "جاهزية التعافي من الكوارث", description: "آخر نسخة احتياطية وآخر اختبار استعادة، من `/api/v1/system/dr-probe`.", manageBackups: "إدارة النسخ الاحتياطي", lastBackup: "آخر نسخة احتياطية", noBackup: "لا توجد نسخة بعد", lastRestoreTest: "آخر اختبار استعادة", notRun: "لم يُجرَ بعد", succeeded: "نجح", failed: "فشل" },
  monitoring: { title: "إشارات المتابعة", description: "استخدم سجل الأخطاء والتحليلات عند ظهور انقطاع أو تباطؤ للتأكد من أثره على تجربة المستخدم.", errorLog: "سجل الأخطاء" }
} as const;
