export const types = {
  eyebrow: "تنظيم البيانات", title: "الأنواع", description: "عرّف مخططات البيانات والحقول وصلاحيات كل دور قبل إدخال السجلات إلى الأرشيف.", count: "{count} نوع", importDefaults: "استيراد التصنيفات الافتراضية", newType: "نوع جديد",
  loadError: "تعذر تحميل الأنواع.", defaultsComplete: "كل التصنيفات الافتراضية موجودة بالفعل — لم يتغير شيء.", defaultsPartial: "استُورد {imported} من {total}؛ توقف عند «{name}»: {error}", defaultsImported: "استُوردت {count} تصنيفات افتراضية دون المساس بالأنواع الموجودة.", editLoadError: "تعذر تحميل النوع للتحرير.", saveError: "تعذر حفظ النوع. تحقق من البيانات ثم أعد المحاولة.", saved: "تم حفظ النوع «{name}».", deleteTitle: "حذف النوع", deleteMessage: "هل تريد حذف النوع «{name}»؟ لا يمكن التراجع عن هذا الإجراء.", delete: "حذف", deleteError: "تعذر حذف النوع. حاول مجددًا.", deleted: "تم حذف النوع «{name}».",
  impactTitle: "معاينة أثر المخطط", impactDescription: "تغيير الحقول أو حذف النوع قد يجعل بيانات السجلات الحالية غير متوافقة. راجع الحقول والصلاحيات قبل الحفظ؛ الحذف لا يمكن التراجع عنه.", retry: "إعادة المحاولة", loading: "جارٍ تحميل الأنواع…", availableSchemas: "المخططات المتاحة", archiveTypes: "أنواع الأرشيف", refreshing: "جارٍ التحديث…", schemaPreview: "معاينة المخطط", edit: "تحرير", emptyTitle: "اختر نوعًا لمعاينة حقوله", emptyDescription: "أو أنشئ نوعًا جديدًا للبدء في تنظيم بيانات الأرشيف.", editorPlaceholder: "اختر «نوع جديد» أو حرّر نوعًا موجودًا لتعديل المخطط.",
  fieldTypes: { text: "نص", number: "رقم", date: "تاريخ", select: "اختيار واحد", multi: "اختيارات متعددة", boolean: "نعم / لا" },
  typeIdRequired: "أدخل معرّف النوع.", typeNameRequired: "أدخل اسم النوع.", fieldNameRequired: "أدخل اسمًا لهذا الحقل.", conditionRequired: "أدخل الحقل المصدر وقيمة المقارنة لهذا العرض المشروط.", formIdentityRequired: "أدخل معرّف النوع واسمه قبل الحفظ.", formFieldsRequired: "أدخل اسمًا لكل حقل قبل الحفظ.", duplicateFields: "أسماء بعض الحقول مكررة. استخدم اسمًا فريدًا لكل حقل.", conditionalFieldsRequired: "أدخل الحقل المصدر وقيمة المقارنة لكل عرض مشروط قبل الحفظ.",
  editType: "تحرير النوع", unnamedType: "نوع غير مسمى", createSchema: "إنشاء مخطط بيانات", close: "إغلاق", unsavedDraft: "يوجد نوع غير محفوظ من {date}. استعادته؟", restoreDraft: "استعادة المسودة", discard: "تجاهل", typeId: "معرّف النوع", typeIdEditHint: "لا يمكن تغيير المعرّف بعد الإنشاء.", typeIdCreateHint: "استخدم معرّفًا ثابتًا مثل document أو photo.", typeName: "اسم النوع", typeNamePlaceholder: "مثال: مستند", typeIcon: "أيقونة النوع", selectTypeIcon: "اختر أيقونة النوع", fields: "الحقول", fieldsHint: "حدّد الحقول التي تظهر عند إدخال سجل من هذا النوع، ثم امنح الأدوار صلاحية العرض أو التحرير.", fieldNumber: "الحقل {number}", fieldName: "اسم الحقل", fieldNamePlaceholder: "مثال: جهة الإصدار", duplicateFieldName: "اسم الحقل «{name}» مكرر.", dataType: "نوع البيانات", conditionalDisplay: "عرض مشروط", sourceField: "الحقل المصدر", selectSourceField: "اختر الحقل المصدر", equals: "يساوي", canView: "يمكن العرض", canEdit: "يمكن التحرير", roles: { viewer: "مشاهد", editor: "محرر", admin: "مدير" }, addField: "إضافة حقل", saving: "جارٍ الحفظ…", saveType: "حفظ النوع", cancel: "إلغاء",
  list: { emptyTitle: "لا توجد أنواع معرفة بعد", emptyDescription: "أنشئ نوعًا لتحديد حقول البيانات والصلاحيات التي يحتاجها فريق الأرشفة.", createFirst: "إنشاء أول نوع", ariaLabel: "الأنواع المعرفة", fields: "{count} حقول", actions: "إجراءات {name}", deleting: "جارٍ الحذف…" }
} as const;
