import { randomBytes } from "node:crypto";

const PROBE_VALUE = "archive-setup-probe";
const DEFAULT_TIMEOUT_MS = 5_000;
const NAMESPACE_PREFIX = "archive-setup-probe-";

class ProbeTimeoutError extends Error {}

function result(ok, code, message, backend, nextActions = []) {
  return { ok, code, message, details: { backend }, nextActions };
}

function unavailable(backend) {
  const names = { postgres: "PostgreSQL", redis: "Redis", storage: "Storage" };
  return result(
    false,
    `${backend.toUpperCase()}_UNAVAILABLE`,
    `${names[backend]} probe could not complete.`,
    backend,
    [`Verify the ${names[backend]} endpoint and limited probe account, then retry.`],
  );
}

function timeout(backend) {
  const names = { postgres: "PostgreSQL", redis: "Redis", storage: "Storage" };
  return result(
    false,
    `${backend.toUpperCase()}_TIMEOUT`,
    `${names[backend]} probe timed out without changing user data.`,
    backend,
    [`Verify network reachability and retry the ${names[backend]} probe.`],
  );
}

function cleanupFailed(backend) {
  const names = { redis: "Redis", storage: "Storage" };
  return result(
    false,
    `${backend.toUpperCase()}_CLEANUP_FAILED`,
    `${names[backend]} probe cleanup could not be confirmed.`,
    backend,
    [`Remove the generated ${names[backend]} probe namespace before retrying.`],
  );
}

function requireMethod(adapter, method, backend) {
  if (!adapter || typeof adapter[method] !== "function") throw new Error(`${backend} probe adapter is incomplete.`);
}

function createTimeout(timeoutMs) {
  if (!Number.isInteger(timeoutMs) || timeoutMs < 1) throw new Error("timeoutMs must be a positive integer.");
  return timeoutMs;
}

async function bounded(operation, timeoutMs, { onLateCompletion } = {}) {
  const controller = new AbortController();
  let timedOut = false;
  let timer;
  const pending = Promise.resolve().then(() => operation({ signal: controller.signal }));
  if (onLateCompletion) {
    pending.then(
      () => { if (timedOut) void Promise.resolve(onLateCompletion()).catch(() => {}); },
      () => { if (timedOut) void Promise.resolve(onLateCompletion()).catch(() => {}); },
    );
  }
  try {
    return await Promise.race([
      pending,
      new Promise((_, reject) => {
        timer = setTimeout(() => {
          timedOut = true;
          controller.abort();
          reject(new ProbeTimeoutError("probe timed out"));
        }, timeoutMs);
      }),
    ]);
  } finally {
    clearTimeout(timer);
  }
}

async function scopedCleanup(adapter, method, target, backend, timeoutMs) {
  try {
    await bounded(({ signal }) => adapter[method](target, { signal }), timeoutMs);
    return null;
  } catch {
    return cleanupFailed(backend);
  }
}

export function createProbeNamespace() {
  return `${NAMESPACE_PREFIX}${randomBytes(12).toString("hex")}`;
}

function safeNamespace(value) {
  if (typeof value !== "string" || !new RegExp(`^${NAMESPACE_PREFIX}[A-Za-z0-9_-]+$`).test(value)) {
    throw new Error("Probe namespace must be generated by createProbeNamespace.");
  }
  return value;
}

export function createDataProbes({ postgres, redis, storage, timeoutMs = DEFAULT_TIMEOUT_MS, createNamespace = createProbeNamespace } = {}) {
  const limit = createTimeout(timeoutMs);

  const probePostgres = async () => {
    try {
      requireMethod(postgres, "query", "PostgreSQL");
      await bounded(({ signal }) => postgres.query("SELECT 1 AS archive_probe", { signal }), limit);
      return result(true, "POSTGRES_READY", "PostgreSQL connection and limited read permission verified.", "postgres");
    } catch (error) {
      return error instanceof ProbeTimeoutError ? timeout("postgres") : unavailable("postgres");
    }
  };

  const probeRedis = async () => {
    let key;
    let outcome;
    const cleanup = () => scopedCleanup(redis, "del", key, "redis", limit);
    try {
      requireMethod(redis, "ping", "Redis");
      requireMethod(redis, "set", "Redis");
      requireMethod(redis, "del", "Redis");
      key = `${safeNamespace(createNamespace())}:redis`;
      const pong = await bounded(({ signal }) => redis.ping({ signal }), limit);
      if (String(pong).toUpperCase() !== "PONG") throw new Error("Redis PING did not return PONG.");
      await bounded(({ signal }) => redis.set(key, PROBE_VALUE, { signal }), limit, { onLateCompletion: cleanup });
      requireMethod(redis, "get", "Redis");
      if (await bounded(({ signal }) => redis.get(key, { signal }), limit) !== PROBE_VALUE) throw new Error("Redis probe value did not match.");
      outcome = result(true, "REDIS_READY", "Redis connection and temporary namespace permission verified.", "redis");
    } catch (error) {
      outcome = error instanceof ProbeTimeoutError ? timeout("redis") : unavailable("redis");
    }
    const cleanupOutcome = key ? await cleanup() : null;
    return cleanupOutcome || outcome;
  };

  const probeStorage = async () => {
    let path;
    let outcome;
    const cleanup = () => scopedCleanup(storage, "remove", path, "storage", limit);
    try {
      requireMethod(storage, "write", "Storage");
      requireMethod(storage, "remove", "Storage");
      path = `${safeNamespace(createNamespace())}/storage-probe.txt`;
      await bounded(({ signal }) => storage.write(path, PROBE_VALUE, { signal }), limit, { onLateCompletion: cleanup });
      requireMethod(storage, "read", "Storage");
      if (await bounded(({ signal }) => storage.read(path, { signal }), limit) !== PROBE_VALUE) throw new Error("Storage probe value did not match.");
      outcome = result(true, "STORAGE_READY", "Storage write, read, and scoped cleanup permission verified.", "storage");
    } catch (error) {
      outcome = error instanceof ProbeTimeoutError ? timeout("storage") : unavailable("storage");
    }
    const cleanupOutcome = path ? await cleanup() : null;
    return cleanupOutcome || outcome;
  };

  return { postgres: probePostgres, redis: probeRedis, storage: probeStorage, all: async () => ({ postgres: await probePostgres(), redis: await probeRedis(), storage: await probeStorage() }) };
}
