import { randomBytes } from "node:crypto";

const PROBE_VALUE = "archive-setup-probe";
const DEFAULT_TIMEOUT_MS = 5_000;
const NAMESPACE_PREFIX = "archive-setup-probe-";

class ProbeTimeoutError extends Error {}

function result(ok, code, message, backend, nextActions = []) {
  return { ok, code, message, details: { backend }, nextActions };
}

function unavailable(backend) {
  const names = { postgres: "PostgreSQL", redis: "Redis", storage: "Storage" };
  return result(
    false,
    `${backend.toUpperCase()}_UNAVAILABLE`,
    `${names[backend]} probe could not complete.`,
    backend,
    [`Verify the ${names[backend]} endpoint and limited probe account, then retry.`],
  );
}

function timeout(backend) {
  const names = { postgres: "PostgreSQL", redis: "Redis", storage: "Storage" };
  return result(
    false,
    `${backend.toUpperCase()}_TIMEOUT`,
    `${names[backend]} probe timed out without changing user data.`,
    backend,
    [`Verify network reachability and retry the ${names[backend]} probe.`],
  );
}

function requireMethod(adapter, method, backend) {
  if (!adapter || typeof adapter[method] !== "function") throw new Error(`${backend} probe adapter is incomplete.`);
}

function createTimeout(timeoutMs) {
  if (!Number.isInteger(timeoutMs) || timeoutMs < 1) throw new Error("timeoutMs must be a positive integer.");
  return timeoutMs;
}

async function bounded(operation, timeoutMs) {
  let timer;
  try {
    return await Promise.race([
      Promise.resolve().then(operation),
      new Promise((_, reject) => { timer = setTimeout(() => reject(new ProbeTimeoutError("probe timed out")), timeoutMs); }),
    ]);
  } finally {
    clearTimeout(timer);
  }
}

export function createProbeNamespace() {
  return `${NAMESPACE_PREFIX}${randomBytes(12).toString("hex")}`;
}

function safeNamespace(value) {
  if (typeof value !== "string" || !new RegExp(`^${NAMESPACE_PREFIX}[A-Za-z0-9_-]+$`).test(value)) {
    throw new Error("Probe namespace must be generated by createProbeNamespace.");
  }
  return value;
}

export function createDataProbes({ postgres, redis, storage, timeoutMs = DEFAULT_TIMEOUT_MS, createNamespace = createProbeNamespace } = {}) {
  const limit = createTimeout(timeoutMs);

  const probePostgres = async () => {
    try {
      requireMethod(postgres, "query", "PostgreSQL");
      await bounded(() => postgres.query("SELECT 1 AS archive_probe"), limit);
      return result(true, "POSTGRES_READY", "PostgreSQL connection and limited read permission verified.", "postgres");
    } catch (error) {
      return error instanceof ProbeTimeoutError ? timeout("postgres") : unavailable("postgres");
    }
  };

  const probeRedis = async () => {
    let key;
    try {
      requireMethod(redis, "ping", "Redis");
      requireMethod(redis, "set", "Redis");
      requireMethod(redis, "del", "Redis");
      key = `${safeNamespace(createNamespace())}:redis`;
      const pong = await bounded(() => redis.ping(), limit);
      if (String(pong).toUpperCase() !== "PONG") throw new Error("Redis PING did not return PONG.");
      await bounded(() => redis.set(key, PROBE_VALUE), limit);
      requireMethod(redis, "get", "Redis");
      if (await bounded(() => redis.get(key), limit) !== PROBE_VALUE) throw new Error("Redis probe value did not match.");
      return result(true, "REDIS_READY", "Redis connection and temporary namespace permission verified.", "redis");
    } catch (error) {
      return error instanceof ProbeTimeoutError ? timeout("redis") : unavailable("redis");
    } finally {
      if (key) {
        try { await bounded(() => redis.del(key), limit); } catch { /* cleanup is intentionally best-effort and remains namespace-scoped */ }
      }
    }
  };

  const probeStorage = async () => {
    let path;
    try {
      requireMethod(storage, "write", "Storage");
      requireMethod(storage, "remove", "Storage");
      path = `${safeNamespace(createNamespace())}/storage-probe.txt`;
      await bounded(() => storage.write(path, PROBE_VALUE), limit);
      requireMethod(storage, "read", "Storage");
      if (await bounded(() => storage.read(path), limit) !== PROBE_VALUE) throw new Error("Storage probe value did not match.");
      return result(true, "STORAGE_READY", "Storage write, read, and scoped cleanup permission verified.", "storage");
    } catch (error) {
      return error instanceof ProbeTimeoutError ? timeout("storage") : unavailable("storage");
    } finally {
      if (path) {
        try { await bounded(() => storage.remove(path), limit); } catch { /* cleanup is intentionally best-effort and remains namespace-scoped */ }
      }
    }
  };

  return { postgres: probePostgres, redis: probeRedis, storage: probeStorage, all: async () => ({ postgres: await probePostgres(), redis: await probeRedis(), storage: await probeStorage() }) };
}
