import { spawnSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, unlinkSync, writeFileSync } from "node:fs";
import { basename, dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const MODULE_PATH = fileURLToPath(import.meta.url);
const ROOT = resolve(dirname(MODULE_PATH), "..");
const DEFAULT_COMPOSE = join(ROOT, "infra", "docker-compose.yml");
const secretPattern = /(?:password|passwd|secret|token|access_token|client_secret|api[_-]?key|app_key|private_key|authorization)/i;

export const SCENARIOS = Object.freeze([
  { id: "GD-DB-01", title: "PostgreSQL outage", service: "postgres", execution: "docker", detection: "Deep health reports database unavailable; API writes fail closed.", recovery: "Restore PostgreSQL, wait for health, and rerun the read/write smoke probe.", dataSafety: "Never delete or recreate the named database volume.", externalRequirements: "Native service-manager recovery must be recorded externally; no native command is run." },
  { id: "GD-REDIS-02", title: "Redis outage", service: "redis", execution: "docker", detection: "Deep health and queue/cache probes report Redis unavailable.", recovery: "Restore Redis, wait for health, and confirm queue processing resumes.", dataSafety: "No FLUSHALL, eviction-policy change, or volume deletion is allowed.", externalRequirements: "Native service-manager recovery must be recorded externally; no native command is run." },
  { id: "GD-WORKER-03", title: "Queue worker outage", service: "laravel-worker", execution: "docker", detection: "Operator snapshot reports a missing worker and queue backlog.", recovery: "Restart the worker and confirm its health check plus queue drain.", dataSafety: "Jobs are paused, not removed or retried destructively.", externalRequirements: "Native service-manager recovery must be recorded externally; no native command is run." },
  { id: "GD-REVERB-04", title: "Reverb outage", service: "laravel-reverb", execution: "docker", detection: "Operator snapshot reports the Reverb listener unavailable.", recovery: "Restart Reverb and confirm the TCP health check.", dataSafety: "The fault never modifies database, cache, or storage volumes.", externalRequirements: "Native service-manager recovery must be recorded externally; no native command is run." },
  { id: "GD-NET-05", title: "Application network interruption", service: "laravel", execution: "docker", detection: "Public health requests fail while the isolated Compose project remains inspectable.", recovery: "Unpause the Laravel gateway and rerun health.", dataSafety: "Uses Docker pause/unpause only; no host firewall or public network changes.", externalRequirements: "Native service-manager recovery must be recorded externally; no native command is run." },
  { id: "GD-DISK-06", title: "Ephemeral disk pressure", service: "laravel-fpm", execution: "docker", detection: "A bounded temporary file causes the application process to report storage pressure.", recovery: "Remove only the runner-owned /tmp file and rerun health.", dataSafety: "Requires explicit disk opt-in; writes only a bounded temporary file in the isolated container.", externalRequirements: "Native service-manager recovery must be recorded externally; no native command is run." },
  { id: "GD-CERT-07", title: "Public certificate failure", service: null, execution: "external-manual", detection: "Validate public TLS expiry, chain, hostname, and renewal alert from a real public endpoint.", recovery: "Follow the deployed edge certificate renewal runbook and preserve its external evidence.", dataSafety: "No public certificate, DNS record, or edge configuration is changed by this runner.", externalRequirements: "Native and real public-certificate checks are external/manual requirements and are never executed or passed by this runner." },
]);

export function redactEvidence(value) {
  return String(value ?? "")
    .replace(/([?&](?:password|token|access_token|api[_-]?key|client_secret)=)[^&#\s]+/gi, "$1[REDACTED]")
    .replace(/(password|passwd|secret|token|access_token|client_secret|api[_-]?key|app_key|private_key)\s*[:=]\s*(?:"(?:\\.|[^"])*"|'(?:\\.|[^'])*'|[^\s,;&]+)/gi, "$1=[REDACTED]")
    .replace(/Authorization\s*:\s*(?:Bearer|Basic)\s+[^\s]+/gi, "Authorization: [REDACTED]")
    .replace(/([a-z][a-z0-9+.-]*:\/\/)[^\s/@:]+:[^\s/@]+@/gi, "$1[REDACTED]@")
    .replace(/(?:[A-Za-z]:\\|\/)(?:[^\s"']+[\\/])+[^\s"']*/g, "[REDACTED_PATH]");
}

function isolatedCompose(source, projectName) {
  const raw = readFileSync(source, "utf8");
  const stripped = raw.replace(/^\s*container_name:\s*.*(?:\r?\n|$)/gm, "");
  return `# Generated by scripts/game-day.mjs for ${projectName}; never commit.\n# Fixed container_name: entries are removed so Docker Compose project scoping isolates this drill.\n${stripped}`;
}

function actionFor(scenario) {
  if (scenario.execution !== "docker") return [];
  if (scenario.id === "GD-NET-05") return [["pause", scenario.service], ["unpause", scenario.service]];
  if (scenario.id === "GD-DISK-06") return [["exec", "-T", scenario.service, "sh", "-lc", "dd if=/dev/zero of=/tmp/archive-game-day-fill bs=1M count=${GAME_DAY_DISK_MB:-128} conv=fsync"], ["exec", "-T", scenario.service, "sh", "-lc", "rm -f /tmp/archive-game-day-fill"]];
  return [["stop", scenario.service], ["start", scenario.service]];
}

function dockerCommand(args, purpose, expect = "success") { return { command: "docker", args, purpose, expect }; }

export function createGameDayPlan({ scenarioIds = SCENARIOS.map((scenario) => scenario.id), dryRun = true, projectName = `archive-gameday-${Date.now().toString(36)}`, composeFile = DEFAULT_COMPOSE } = {}) {
  const wanted = new Set(scenarioIds);
  const scenarios = SCENARIOS.filter((scenario) => wanted.has(scenario.id));
  if (scenarios.length !== wanted.size) throw new Error("Unknown game-day scenario requested");
  if (!/^archive-gameday-[a-z0-9-]+$/.test(projectName)) throw new Error("Game-day project name must be archive-gameday-* for scoped cleanup");
  const generatedPath = join(dirname(composeFile), `.${projectName}.compose.yml`);
  const composeArgs = ["compose", "--project-name", projectName, "--file", generatedPath];
  const commands = [dockerCommand(["version", "--format", "{{.Server.Version}}"], "verify-docker-runtime"), dockerCommand([...composeArgs, "config"], "validate-isolated-compose"), dockerCommand([...composeArgs, "up", "--detach", "--wait"], "start-isolated-stack")];
  for (const scenario of scenarios) {
    const actions = actionFor(scenario);
    if (!actions.length) continue;
    commands.push(dockerCommand([...composeArgs, ...actions[0]], `fault-${scenario.id}`));
    commands.push(dockerCommand([...composeArgs, "ps", "--all", "--format", "json"], `detect-${scenario.id}`, "service-down"));
    commands.push(dockerCommand([...composeArgs, ...actions[1]], `restore-${scenario.id}`));
    commands.push(dockerCommand([...composeArgs, "ps", "--all", "--format", "json"], `recover-${scenario.id}`, "service-running"));
    commands.push(dockerCommand([...composeArgs, "exec", "-T", "postgres", "sh", "-lc", "pg_isready -U \"$POSTGRES_USER\" -d \"$POSTGRES_DB\""], `data-integrity-${scenario.id}`));
  }
  commands.push(dockerCommand([...composeArgs, "down", "--volumes", "--remove-orphans"], "scoped-cleanup"));
  commands.push(dockerCommand([...composeArgs, "ps", "--all", "--format", "json"], "verify-scoped-cleanup"));
  return { runtime: "docker-compose", dryRun, projectName, composeFile, generatedCompose: { path: generatedPath, contents: isolatedCompose(composeFile, projectName) }, scenarios, commands };
}

function safeEvidence(value) {
  if (Array.isArray(value)) return value.map(safeEvidence);
  if (value && typeof value === "object") return Object.fromEntries(Object.entries(value).map(([key, item]) => [key, secretPattern.test(key) ? "[REDACTED]" : safeEvidence(item)]));
  return typeof value === "string" ? redactEvidence(value) : value;
}

function defaultRun(command, args) { return spawnSync(command, args, { encoding: "utf8", windowsHide: true }); }

function satisfiesExpectation(command, result) {
  if (result.status !== 0) return false;
  if (command.expect === "success") return true;
  let records;
  try { const parsed = JSON.parse(String(result.stdout || "")); records = Array.isArray(parsed) ? parsed : [parsed]; } catch { return false; }
  const service = command.purpose.replace(/^(detect|recover)-/, "").replace(/^GD-[A-Z]+-\d+$/, "");
  const scenario = SCENARIOS.find((item) => command.purpose.endsWith(item.id));
  const row = records.find((item) => item.Service === scenario?.service);
  if (!row) return false;
  const state = String(row.State || row.Status || "").toLowerCase();
  return command.expect === "service-down" ? state !== "running" : state === "running" && String(row.Health || "healthy").toLowerCase() !== "unhealthy";
}

export function runGameDay({ execute = false, outputDir = join(ROOT, "artifacts", "game-day"), now = new Date(), allowDiskFault = false, run = defaultRun, ...options } = {}) {
  const plan = createGameDayPlan({ ...options, dryRun: !execute });
  if (execute && plan.scenarios.some((scenario) => scenario.id === "GD-DISK-06") && !allowDiskFault) throw new Error("GD-DISK-06 requires --allow-disk-fault during an executed drill");
  const records = [];
  let cleanupProved = false;
  let failure = null;
  if (execute) {
    writeFileSync(plan.generatedCompose.path, plan.generatedCompose.contents, { encoding: "utf8", mode: 0o600, flag: "wx" });
    try {
      for (const command of plan.commands) {
        const result = run(command.command, command.args);
        const proved = satisfiesExpectation(command, result);
        records.push({ purpose: command.purpose, expectation: command.expect, status: result.status, proved, stdout: redactEvidence(result.stdout), stderr: redactEvidence(result.stderr) });
        if (command.purpose === "verify-scoped-cleanup") cleanupProved = result.status === 0 && !String(result.stdout ?? "").trim();
        if (!proved && command.purpose !== "verify-scoped-cleanup") { failure = `${command.purpose} failed`; break; }
      }
    } finally {
      if (!records.some((record) => record.purpose === "scoped-cleanup")) {
        const cleanup = plan.commands.find((command) => command.purpose === "scoped-cleanup");
        const result = run(cleanup.command, cleanup.args);
        records.push({ purpose: cleanup.purpose, status: result.status, stdout: redactEvidence(result.stdout), stderr: redactEvidence(result.stderr) });
      }
      if (existsSync(plan.generatedCompose.path)) unlinkSync(plan.generatedCompose.path);
    }
  }
  const evidence = safeEvidence({ schemaVersion: 1, generatedAt: now.toISOString(), status: execute ? (failure ? "failed" : "completed") : "planned", runner: { runtime: plan.runtime, projectName: plan.projectName, dryRun: plan.dryRun }, scenarios: plan.scenarios.map((scenario) => ({ id: scenario.id, status: scenario.execution === "external-manual" ? "external-manual-required" : (execute ? (failure ? "not-proven" : "executed") : "planned"), detection: scenario.detection, recovery: scenario.recovery, dataSafety: scenario.dataSafety, externalRequirements: scenario.externalRequirements })), cleanup: { scope: plan.projectName, requested: true, proofRequired: true, proved: cleanupProved }, commands: records });
  mkdirSync(outputDir, { recursive: true });
  const evidencePath = join(outputDir, `v1-501-game-day-${now.toISOString().replace(/[:.]/g, "-")}.json`);
  writeFileSync(evidencePath, JSON.stringify(evidence, null, 2), { encoding: "utf8", mode: 0o600 });
  return { ...evidence, dryRun: plan.dryRun, evidencePath };
}

if (process.argv[1] && resolve(process.argv[1]) === resolve(MODULE_PATH)) {
  const args = new Set(process.argv.slice(2));
  const scenarioIds = process.argv.slice(2).filter((arg) => arg.startsWith("GD-"));
  const result = runGameDay({ execute: args.has("--execute"), allowDiskFault: args.has("--allow-disk-fault"), scenarioIds: scenarioIds.length ? scenarioIds : undefined });
  console.log(JSON.stringify({ status: result.status, dryRun: result.runner.dryRun, evidencePath: result.evidencePath }, null, 2));
  if (result.status === "failed") process.exitCode = 1;
}
