FROM debian:bookworm-slim

ENV container=docker

RUN apt-get update \
    && apt-get install -y --no-install-recommends systemd systemd-sysv ca-certificates curl libatomic1 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && systemctl mask systemd-logind.service getty@.service console-getty.service

STOPSIGNAL SIGRTMIN+3
CMD ["/sbin/init"]
