"use client";
import { useEffect, useMemo, useState } from "react";
import type { FormEvent } from "react";
import AppShell from "@/components/AppShell";
import PageToolbar from "@/components/PageToolbar";
import EmptyState from "@/components/EmptyState";
import { createArchiveApiClient, type Project, type ProjectTask, type ProjectTaskStatus } from "@/lib/archive-api";

const columns: Array<[ProjectTaskStatus, string]> = [["todo", "للعمل"], ["in_progress", "قيد التنفيذ"], ["review", "للمراجعة"], ["done", "مكتملة"]];
export default function ProjectTasksPage() {
 const api=useMemo(()=>createArchiveApiClient(),[]); const [projects,setProjects]=useState<Project[]>([]); const [tasks,setTasks]=useState<ProjectTask[]>([]); const [projectId,setProjectId]=useState(""); const [title,setTitle]=useState(""); const [assignee,setAssignee]=useState(""); const [recordId,setRecordId]=useState(""); const [status,setStatus]=useState("");
 const load=async()=>{const [p,t]=await Promise.all([api.projects(),api.projectTasks()]);if(p.ok)setProjects(p.projects);if(t.ok)setTasks(t.tasks);}; useEffect(()=>{void load();},[]);
 async function create(e:FormEvent){e.preventDefault();if(!projectId||!title.trim())return;const r=await api.createProjectTask({projectId,title:title.trim(),status:"todo",assignee:assignee||null,recordId:recordId||null,dueDate:null});if(!r.ok)return setStatus(r.error||"تعذر إنشاء المهمة.");setTasks(x=>[r.task,...x]);setTitle("");setAssignee("");setRecordId("");setStatus("تم إنشاء المهمة.");}
 async function move(task:ProjectTask,next:ProjectTaskStatus){const r=await api.updateProjectTask(task.id,{status:next});if(!r.ok)return setStatus(r.error||"تعذر تحديث الحالة.");setTasks(x=>x.map(t=>t.id===task.id?r.task:t));}
 return <AppShell subtitle="مهام المشاريع" contentClassName="stack"><PageToolbar title="لوحة مهام المشاريع" description="مهام مستقلة مرتبطة بمشروع، مع مكلّف وتاريخ تحديث وربط اختياري بسجل أرشيفي." actions={<a className="button button-secondary" href="/kanban">كانبان السجلات</a>}/><form className="panel archive-toolbar-grid" onSubmit={create}><label>المشروع<select value={projectId} onChange={e=>setProjectId(e.target.value)} required><option value="">اختر مشروعاً</option>{projects.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><label>المهمة<input value={title} onChange={e=>setTitle(e.target.value)} required /></label><label>المكلّف<input value={assignee} onChange={e=>setAssignee(e.target.value)} /></label><label>معرّف المادة (اختياري)<input value={recordId} onChange={e=>setRecordId(e.target.value)} /></label><button className="button button-primary">إضافة مهمة</button></form>{status?<p className="form-status">{status}</p>:null}{tasks.length?<section className="workflow-board">{columns.map(([key,label])=><article className="workflow-column" key={key}><h2>{label}</h2>{tasks.filter(t=>t.status===key).map(t=><div className="kanban-card" key={t.id}><strong>{t.title}</strong><small>{projects.find(p=>p.id===t.projectId)?.name||t.projectId} · {t.assignee||"غير مسند"}</small>{t.recordId?<a href={`/archive/${encodeURIComponent(t.recordId)}`}>المادة المرتبطة</a>:null}<select value={t.status} onChange={e=>void move(t,e.target.value as ProjectTaskStatus)}>{columns.map(([v,l])=><option value={v} key={v}>{l}</option>)}</select><small>آخر تحديث: {new Date(t.updatedAt).toLocaleString("ar-SA")}</small></div>)}</article>)}</section>:<EmptyState title="لا توجد مهام بعد" description="أضف أول مهمة إلى مشروع عمل."/>}</AppShell>;
}
