export const firstRun = {
  subtitle: "First run", navLabel: "Setup journey", eyebrow: "First run", title: "Set up {brand}", description: "Follow the current step, then complete the instructions for the path you selected. Sign-in appears only when it is needed to resume setup.", stages: "organization stages complete", readiness: "Readiness", healthCheck: "Check health", help: "Help", openWorkspace: "Open workspace", journey: "Unified setup journey", currentStep: "Current step", readinessLabel: "System readiness", skip: "Skip the settings review for an expert user", skipHelp: "This skips only the settings review; it never bypasses the server check or sign-in.", step: "Step", choose: "Choose a setup path", presetLabel: "Choose a setup preset", setupHelp: "Both paths use setup.bat as a safe interface for scripts/control-center.mjs; secrets appear only when the administrator password is generated for the first time.", selectedSteps: "Selected setup steps", server: "Server", connected: "Connected", checking: "Checking", offline: "Offline", notChecked: "Not checked", startHealth: "Use Check health after starting the stack.", startupReady: "Startup readiness", complete: "Complete", configuring: "Being configured", completeHelp: "The startup reminder will no longer appear in pages.", incompleteHelp: "Complete the steps, or open the tour later from Help or Settings.", orgStages: "Organization first-use stages", orgHelp: "This organization-wide state is saved and resumes after sign-in or on another device.", retry: "Try again", signInHelp: "Sign in to view the saved organization progress and resume the next step.", signIn: "Sign in", loadingProgress: "Loading first-run progress…", undo: "Mark incomplete", mark: "Mark complete", stage: "Stage", defaults: "Ready-to-use default types and tags", defaultsHelp: "Optional, additive imports only — they never overwrite an existing type or tag.", importTypes: "Import default types", importTags: "Import default tags", feedback: "Interactive test notes", feedbackHelp: "Record any change needed during testing. Notes stay on this device; then copy them into the follow-up conversation.", feedbackLabel: "Interactive test notes", feedbackPlaceholder: "Example: On the add-record step, I would like the classification field to be simpler…", copyNotes: "Copy test notes", copied: "Copied. Paste the notes into the follow-up conversation.", copyFailed: "Could not copy automatically. Copy the text from the field and send it in the follow-up conversation.", security: "Safe first-run reminders", apiError: "Could not reach the API.", progressError: "Could not load first-run progress.", progressSaveError: "Could not save first-run progress.", notesHeading: "Interactive test notes",
  uptime: { unknown: "Unknown", seconds: "{count} seconds", minutes: "{count} minutes", hoursAndMinutes: "{hours} hours {minutes} minutes" },
  journeySteps: { server: { title: "Start the server", description: "Checks the API and data engine automatically." }, account: { title: "Confirm sign-in", description: "Sign in when needed to resume saved setup." }, settings: { title: "Review settings", description: "Test connections and review operating settings." }, ready: { title: "Start working", description: "Move to the workspace after readiness is complete." } },
  presetSteps: { stepStatus: "Step {current} of {total}", next: "Next", previous: "Previous", markDone: "Done, next step", finish: "Finish path", completedLabel: "Complete", currentLabel: "Current step" },
  tour: {
    start: "Start guided tour",
    restart: "Restart guided tour",
    progress: "Step {current} of {total}",
    previous: "Previous",
    next: "Next",
    finish: "Finish tour",
    skip: "Skip",
    steps: {
      archive: { title: "Archive", description: "Each record represents an item in your collection, with its metadata and linked files in one place.", action: "Open archive" },
      search: { title: "Search", description: "Search all records, filter by date, type, and status, and save searches you use often.", action: "Open search" },
      uploads: { title: "Add item", description: "Upload individual files or batches while large files are processed in the background without blocking your work.", action: "Start upload" },
      kanban: { title: "Kanban", description: "Track record workflows by status and move records by dragging or with a fully accessible menu.", action: "Open Kanban" },
      settings: { title: "Settings", description: "Customize your preferences, language, and appearance, and manage backups and external integrations.", action: "Open settings" }
    }
  }
} as const;
