export const status = {
  errors: { metricsLoad: "Unable to load system metrics.", unknown: "Unknown error", healthConnection: "Unable to connect to the server", connectionPrefix: "Connection error: {message}" },
  uptime: { day: "d", hour: "h", minute: "m" },
  toolbar: { eyebrow: "Operational monitoring", title: "System status", description: "A quick surface for monitoring server connectivity, data engine, and uptime, with automatic updates every 30 seconds.", connected: "Connected", checking: "Checking", disconnected: "Disconnected", lastChecked: "Last checked: {date}", checkNowAriaLabel: "Check status now", checkNow: "Check now" },
  health: { stable: "Server connection is stable", checking: "Checking the connection", stopped: "Server connection is unavailable", defaultDescription: "This surface shows current backend health and the direct connection heartbeat.", backend: "Backend server", local: "Local", engine: "Data engine", uptime: "Uptime" },
  recovery: { healthCheckFailed: "Unable to complete the health check", retry: "Check again", setupJourney: "Return to setup journey", systemControl: "Open system control", serverReady: "Server step complete", serverReadyDescription: "The server connection is healthy. View the setup journey for the next step and readiness percentage.", continueSetup: "Continue setup journey" },
  check: { ariaLabel: "Check details", title: "Check details", description: "This data relies on the `/api/v1/health` endpoint without changing the backend contract.", autoRefresh: "Automatic refresh", requestStatus: "Request status", pending: "In progress", success: "Successful", failed: "Failed", interval: "Check interval", intervalValue: "30 seconds", lastUpdated: "Last updated" },
  metrics: { ariaLabel: "Live server metrics", title: "Live server metrics", description: "CPU, memory, disk, and queue depth from `/api/v1/system/status` (administrators only).", cpu: "CPU load", memory: "Memory", disk: "Disk", queueDepth: "Queue depth", unavailable: "Unavailable", loadError: "Unable to load system metrics" },
  disasterRecovery: { ariaLabel: "Disaster recovery readiness", title: "Disaster recovery readiness", description: "Latest backup and restore test from `/api/v1/system/dr-probe`.", manageBackups: "Manage backups", lastBackup: "Latest backup", noBackup: "No backup yet", lastRestoreTest: "Latest restore test", notRun: "Not run yet", succeeded: "Succeeded", failed: "Failed" },
  monitoring: { title: "Monitoring signals", description: "Use the error log and analytics when an outage or slowdown occurs to understand its effect on the user experience.", errorLog: "Error log" }
} as const;
