export const types = {
  eyebrow: "Data organization", title: "Types", description: "Define data schemas, fields, and role permissions before adding records to the archive.", count: "{count} types", importDefaults: "Import default classifications", newType: "New type",
  loadError: "Could not load types.", defaultsComplete: "All default classifications already exist — nothing changed.", defaultsPartial: "Imported {imported} of {total}; stopped at “{name}”: {error}", defaultsImported: "Imported {count} default classifications without changing existing types.", editLoadError: "Could not load the type for editing.", saveError: "Could not save the type. Check the data and try again.", saved: "Saved type “{name}”.", deleteTitle: "Delete type", deleteMessage: "Do you want to delete type “{name}”? This action cannot be undone.", delete: "Delete", deleteError: "Could not delete the type. Try again.", deleted: "Deleted type “{name}”.",
  impactTitle: "Schema impact preview", impactDescription: "Changing fields or deleting a type can make current record data incompatible. Review fields and permissions before saving; deletion cannot be undone.", retry: "Try again", loading: "Loading types…", availableSchemas: "Available schemas", archiveTypes: "Archive types", refreshing: "Refreshing…", schemaPreview: "Schema preview", edit: "Edit", emptyTitle: "Select a type to preview its fields", emptyDescription: "Or create a new type to start organizing archive data.", editorPlaceholder: "Select “New type” or edit an existing type to change the schema.",
  fieldTypes: { text: "Text", number: "Number", date: "Date", select: "Single select", multi: "Multiple select", boolean: "Yes / no" },
  typeIdRequired: "Enter a type identifier.", typeNameRequired: "Enter a type name.", fieldNameRequired: "Enter a name for this field.", conditionRequired: "Enter the source field and comparison value for this conditional display.", formIdentityRequired: "Enter the type identifier and name before saving.", formFieldsRequired: "Enter a name for every field before saving.", duplicateFields: "Some field names are duplicated. Use a unique name for each field.", conditionalFieldsRequired: "Enter the source field and comparison value for every conditional display before saving.",
  editType: "Edit type", unnamedType: "Unnamed type", createSchema: "Create data schema", close: "Close", unsavedDraft: "There is an unsaved type from {date}. Restore it?", restoreDraft: "Restore draft", discard: "Discard", typeId: "Type identifier", typeIdEditHint: "The identifier cannot be changed after creation.", typeIdCreateHint: "Use a stable identifier such as document or photo.", typeName: "Type name", typeNamePlaceholder: "For example: Document", typeIcon: "Type icon", selectTypeIcon: "Choose a type icon", fields: "Fields", fieldsHint: "Choose the fields shown when entering a record of this type, then give roles viewing or editing permission.", fieldNumber: "Field {number}", fieldName: "Field name", fieldNamePlaceholder: "For example: Issuing authority", duplicateFieldName: "Field name “{name}” is duplicated.", dataType: "Data type", conditionalDisplay: "Conditional display", sourceField: "Source field", selectSourceField: "Select source field", equals: "Equals", canView: "Can view", canEdit: "Can edit", roles: { viewer: "Viewer", editor: "Editor", admin: "Administrator" }, addField: "Add field", saving: "Saving…", saveType: "Save type", cancel: "Cancel",
  list: { emptyTitle: "No types have been defined yet", emptyDescription: "Create a type to define the data fields and permissions your archive team needs.", createFirst: "Create first type", ariaLabel: "Defined types", fields: "{count} fields", actions: "Actions for {name}", deleting: "Deleting…" }
} as const;
